[package]
name = "apu_tt"
version = "0.1.0"
authors = ["Ivan Tham <pickfire@riseup.net>"]
description = "APU Timetable CLI"
readme = "README.md"

[[bin]]
name = "tt"
path = "src/main.rs"

[dependencies]
error-chain = "0.11.0"
prettytable-rs = "0.6.7"
reqwest = "0.8.4"
serde = "1.0.27"
serde_derive = "1.0.27"
serde_json = "1.0.9"
